### ISSUE TITLE
Wagtail 3.0 support?

### ISSUE THREAD

**Issue by omnivl-lw** [labd/wagtailstreamforms#195]
Hello maintainers,

Are there any plans to introduce wagtail 3.0 support? I'm migrating my site to wagtail 3.0 and would love to use this package.

**Comment by TonisPiip** [comment]
I'm also wanting to update to WT3 but this plugin in blocking.

**Comment by mikaelengstrom** [comment]
@labdigital-builds Any plans on this? If you need help to make it happen, let us know :)

**Comment by VdeJong** [comment]
We're definitely planning on getting wagtailstreamforms wagtail3.x ready. Of course, any help is always appreciated and welcoming.

**Comment by TonisPiip** [comment]
@VdeJong https://github.com/labd/wagtailstreamforms/pull/199

There seems to be a bunch of other forks of this project just updating the setup.py to allow for wagtail v3. 

I tested things and it worked. Please consider approving the merging in the MR.

**Comment by TonisPiip** [comment]
Bump @VdeJong @leongraumans

**Comment by TonisPiip** [comment]
@VdeJong What is stopping us from merging in the PR and making a release?  

The CI is failing I believe, however I'm not familiar with the CI system you have. If that is what's stopping I can look into it and try to solve it, but no idea if the issue is even related to my PR and would like some feedback from the maintainers of this project.
